SELECT * FROM NOTICES ORDER BY REGDATE DESC;
SELECT * FROM NOTICES;
SELECT * FROM NOTICEFILES;



SELECT MAX(CAST(CODE AS INT))+1 FROM NOTICEFILES;




--현재 공지사항에서 최대 값을 가지는 코드를 가져오는 쿼리문 작성해야함. 
SELECT NVL(MAX(TO_NUMBER(CODE)),0) +1 FROM NOTICES; --Oracle
SELECT ISNULL(MAX(CAST(CODE AS INT)),0) FROM NOTICEFILES; --SQL Server



--20개씩 나눈 레코드를 얻어오는 쿼리를 작성하시오. 
--1페이지, 2페이지 얻어오기. 
SELECT * FROM NOTICES ORDER BY REGDATE DESC;
--ROWNUM을 이용한 페이지 나누기 필요. 
SELECT * FROM (SELECT * FROM NOTICES ORDER BY REGDATE DESC) NOTICES WHERE ROWNUM BETWEEN 1 AND 20;

--SQL Server 
SELECT N.* FROM 
(
	SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM, NOTICES.* FROM NOTICES
) N
WHERE N.NUM BETWEEN 11 AND 20;

--prevNotice(우리는 nextNotice)
SELECT * FROM NOTICES ORDER BY REGDATE DESC;
SELECT * FROM NOTICES WHERE REGDATE > (SELECT REGDATE FROM NOTICES WHERE CODE = '240') ORDER BY REGDATE ASC;
--nextNotice(우리는 prevNotice)
SELECT TOP 1 * FROM NOTICES 
WHERE REGDATE < (SELECT REGDATE FROM NOTICES WHERE CODE = '240') 
ORDER BY REGDATE DESC;
--hol.....(홀0홀)




--아까 데이터 다 지웠으니까 하나씩 입력해주자.. INSERT는 조건 안주고 걍 입력임 ㅇㅇ. UPDATE일때 WHERE인고... 
INSERT INTO NOTICES(CODE, TITLE, WRITER, REGDATE, CONTENT, HIT) 
VALUES('146', '제목제목제목제목', 'Namita', SYSDATE, '내용내용내용내용내요용용용용요요용', 3);

INSERT INTO MEMBERS(MID, PWD, NAME) VALUES('Nami', '1234', '남명이');
SELECT * FROM MEMBERS;

--UPDATE NOTICES SET TITLE = '' WHERE WRITER = ''; 

SELECT * FROM (SELECT ROWNUM NUM, N.* FROM (SELECT * FROM NOTICES ORDER BY REGDATE DESC) N) NOTICES WHERE NUM BETWEEN 11 AND 20;

--정렬을 먼저 한 뒤에, 숫자를 붙이고자 했음. SQL Server에서는 정렬된 상태에서 한번에 로우넘 얻어 줄 수 있다.
-- 정렬된 상태에서 로우넘을 주고 별칭 NUM으로 꺼내와달라.
SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM FROM NOTICES;
SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM, NOTICES.* FROM NOTICES;
--NOTICES의 모든 컬럼과 함께 조회 